// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoImobSystem_API.Data;

#nullable disable

namespace NeoImobSystem_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NeoImobSystem_API.Model.Casa", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("NumeroSalas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Casas", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.CasaProprietario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("CasaId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ProprietarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("CasaProprietarios", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Contrato", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("InquilinosId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.ContratoInquilino", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("InquilinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("InquilinoId");

                    b.ToTable("ContratoInquilinos", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Inquilino", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inquilinos", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Proprietario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proprietarios", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Usuario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Casa", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Contrato", "Contrato")
                        .WithOne("Casa")
                        .HasForeignKey("NeoImobSystem_API.Model.Casa", "ContratoId");

                    b.HasOne("NeoImobSystem_API.Model.Usuario", "Usuario")
                        .WithMany("Casas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.CasaProprietario", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Casa", "Casa")
                        .WithMany("CasaProprietarios")
                        .HasForeignKey("CasaId");

                    b.HasOne("NeoImobSystem_API.Model.Proprietario", "Proprietario")
                        .WithMany("CasaProprietarios")
                        .HasForeignKey("ProprietarioId");

                    b.Navigation("Casa");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Contrato", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Usuario", "Usuario")
                        .WithMany("Contratos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.ContratoInquilino", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Contrato", "Contrato")
                        .WithMany("ContratoInquilinos")
                        .HasForeignKey("ContratoId");

                    b.HasOne("NeoImobSystem_API.Model.Inquilino", "Inquilino")
                        .WithMany("ContratoInquilinos")
                        .HasForeignKey("InquilinoId");

                    b.Navigation("Contrato");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Inquilino", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Usuario", "Usuario")
                        .WithMany("Inquilinos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Proprietario", b =>
                {
                    b.HasOne("NeoImobSystem_API.Model.Usuario", "Usuario")
                        .WithMany("Proprietarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Casa", b =>
                {
                    b.Navigation("CasaProprietarios");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Contrato", b =>
                {
                    b.Navigation("Casa")
                        .IsRequired();

                    b.Navigation("ContratoInquilinos");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Inquilino", b =>
                {
                    b.Navigation("ContratoInquilinos");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Proprietario", b =>
                {
                    b.Navigation("CasaProprietarios");
                });

            modelBuilder.Entity("NeoImobSystem_API.Model.Usuario", b =>
                {
                    b.Navigation("Casas");

                    b.Navigation("Contratos");

                    b.Navigation("Inquilinos");

                    b.Navigation("Proprietarios");
                });
#pragma warning restore 612, 618
        }
    }
}
